[package]
name = "xlsx"
version = "0.1.0"
description = "A xlsx file reading and writing library based Serde"
authors = ["John Wang <5672618@qq.com>"]

[dependencies]
serde = "1.0.20"
serde_derive = "1.0.20"
serde-xml-rs = "0.2.1"
