[package]
name = "xlsx"
version = "0.1.0"
description = "A xlsx file reading and writing library based Serde"
authors = ["John Wang <5672618@qq.com>"]

[dependencies]
zip = "0.5.5"
serde = "1.0.111"
serde_derive = "1.0.111"
serde-xml-rs = "0.4.0"